### ISSUE TITLE
Respect base font size

### ISSUE THREAD

**Issue by jerone** [silvestreh/atom-material-ui#182]
Material UI doesn't respect Atom's font size when increasing or decreasing it (trough menu or shortcuts).

I want to decrease the font size as it's a bit big on my screen and would like to put more stuff on it. Compact only works on tree view & tab bar.

***

_Atom 1.5.0-beta0
Material UI https://github.com/silvestreh/atom-material-ui/commit/d7d8ea25d2425cb5980451adc102784261d46822
Windows 7_

**Comment by silvestreh** [comment]
I think you're misunderstanding how those settings work. 

![captura de pantalla 2016-01-27 a las 0 17 02](https://cloud.githubusercontent.com/assets/1133339/12602844/54d9278c-c48b-11e5-860e-d991022910d0.png)

They change the text editor's font size, not the UI. Try this:

- Go to Atom's Settings and find the *"Font Size"* setting within the *Editor Settings* sub-section. (it's a text input, right after *Font Family*)
- Change the font size from the menu I captured in my screenshot.

You will observe how that *"Font size"* changes to a higher or lower value, depending on wether you increased or decreased your font size. This will **only** change the font size of the code you're looking at in the text editor, the rest of the UI will keep the same font size.

There's no code in Material UI that overrides that setting. You can check the `editor.less` file. The only part of that file that affects the text editor is on line 32 and it goes like this:

```less
atom-text-editor, atom-text-editor::shadow {
    text-rendering: optimizeLegibility;

    .find-result {
        .region {
            background: fade(@base-color, 5%);
            border-color: fade(@base-color, 20%);
            border-radius: 0.125rem;
            box-sizing: border-box;
        }
    }
}
```

The rest of the styles in that file are for `[mini]` editors, those single-line text inputs that you can find in the settings-view or the fuzzy finder.

*"OK, What about the font size within the theme's settings?"* – you might ask. Well, that's for scaling the UI. All (or most) of Material UI dimensions are expressed in `rem`s. 

By default, `1rem` equals to `16px`. A button, for example, is `2.25rem` tall, which would render as `36px`. If you change that default value of `16px` to something like `20px` your buttons would be `40px` tall, thus scaling the UI, but maintaining intact your text editor's font size because there are no styles affecting its font-size.

Here's a screenshot with Material UI font size setting set to `25`:

![captura de pantalla 2016-01-27 a las 0 33 58](https://cloud.githubusercontent.com/assets/1133339/12603046/c45ab984-c48d-11e5-9127-20aed473fb87.png)

So you see, Atom's font size only affect the text editor. Material UI's font size affect the entire user interface… minus the text editor :smile: 

Want to fit more stuff into that screen of yours? That's fine, change Material UI's font size to something like `13` to get something like this:

![captura de pantalla 2016-01-27 a las 0 36 54](https://cloud.githubusercontent.com/assets/1133339/12603078/15a0d760-c48e-11e5-9dcb-826fece9ddae.png)

Hope that helps.
