### ISSUE TITLE
Custom font for Theme?

### ISSUE THREAD

**Issue by jamby** [silvestreh/atom-material-ui#213]
Was wondering if there was a way to set a custom font for the Theme, like how you can set a custom font for the actual editor. Not a huge fan of Roboto. Thanks.

**Comment by silvestreh** [comment]
Yes, using your personal stylesheet located in `~/.atom/styles.less`. 

```css
atom-workspace {
    font-family: 'Arial';
}
```
