### ISSUE TITLE
scrollbar is too small in tree view

### ISSUE THREAD

**Issue by seanmars** [silvestreh/atom-material-ui#215]
The scrollbar in tree view is too difficult to drag it. Always drag code or folder

**Comment by silvestreh** [comment]
Here's a quick fix for you. Open your user stylesheet located in `~/.atom/styles.less` and paste this:

```css
.scrollbars-visible-always /deep/::-webkit-scrollbar {
    width: 1rem;
    height: 1rem;
}
```
