### ISSUE TITLE
Git status colors on tree view enhancement

### ISSUE THREAD

**Issue by SpikeShape** [silvestreh/atom-material-ui#217]
Sorry about the weird title of this issue. I didn't know how to call it.

What I am talking about is the git status color in the tree view, when you save a file. It doesn't show them immediately. You have to unfocus and focus it to make it appear.
Edit: I just realized that git status coloring does not apply when the tree is not focused while your file is the marked file.

Additionally when you focus a folder it doesn't show the status.
![bildschirmfoto 2016-02-23 um 08 14 40](https://cloud.githubusercontent.com/assets/7056069/13244313/8ad9e5da-da05-11e5-811d-7ecb510d97da.png)

Also: Is there a way of switching the file icon's color to the color you use or the text? The picture shows a changed js file. I think it used to change the color prior to the last big update.
![bildschirmfoto 2016-02-23 um 08 17 38](https://cloud.githubusercontent.com/assets/7056069/13244366/f899290a-da05-11e5-9047-0dcb18211943.png)

**Comment by SpikeShape** [comment]
Thanks a lot for the update. Yet, the currently selected file is still not marked as changed when the tree view isn't focused.
Unfocused tree:
![bildschirmfoto 2016-02-23 um 17 30 22](https://cloud.githubusercontent.com/assets/7056069/13258368/31127da2-da53-11e5-8049-35dfd3e1b6f1.png)

Focused tree:
![bildschirmfoto 2016-02-23 um 17 31 28](https://cloud.githubusercontent.com/assets/7056069/13258410/50ba02d8-da53-11e5-8c31-21de27752044.png)

**Comment by silvestreh** [comment]
Yes, that's intentional. Otherwise there would be no way to know if the tree view is focused.

**Comment by SpikeShape** [comment]
Fair point...
Could we somehow show that the file, that is currently marked, has been changed / added since the last stage e. g. changing the file name color to yellow / green respectively?

**Comment by silvestreh** [comment]
I'll think of something :smile:

**Comment by jerone** [comment]
What about yellow font color when the tree-view is unfocused? 

| Tree-view focused | Tree-view unfocused | Solution to show git status on unfocused tree-view |
| :--- | :----: | ----: |
| ![focused](https://cloud.githubusercontent.com/assets/55841/13382240/03fd59f6-de70-11e5-9313-0c00c53599d6.png) | ![unfocused](https://cloud.githubusercontent.com/assets/55841/13382242/0db4cd62-de70-11e5-916d-f94ca1ae3a0d.png) | ![solution](https://cloud.githubusercontent.com/assets/55841/13382245/1947d070-de70-11e5-883b-9c71a98e1e54.png) |

It's kinda irritating that the git status isn't show for the last selected file in the tree-view while the focus is on the editor.

**Comment by jerone** [comment]
Adding the following code to my `styles.less` solves it for me:

```css
.tree-view:not(:focus) .list-tree li:not(.list-nested-item):not(.tabBlender).status-modified.selected,
.tree-view:not(:focus) .list-group li:not(.list-nested-item):not(.tabBlender).status-modified.selected,
.tree-view:not(:focus) .list-tree li.list-nested-item > .list-item.status-modified.selected,
.tree-view:not(:focus) .list-group li.list-nested-item > .list-item.status-modified.selected
{
    color: #e3b93c;
}
.tree-view:not(:focus) .list-tree li:not(.list-nested-item):not(.tabBlender).status-added.selected,
.tree-view:not(:focus) .list-group li:not(.list-nested-item):not(.tabBlender).status-added.selected,
.tree-view:not(:focus) .list-tree li.list-nested-item > .list-item.status-added.selected,
.tree-view:not(:focus) .list-group li.list-nested-item > .list-item.status-added.selected
{
    color: #8bc34a;
}
```

Key is `.tree-view:not(:focus)` in front of the selectors.
