### ISSUE TITLE
Add option to change font-smoothing

### ISSUE THREAD

**Issue by davidpmccormick** [silvestreh/atom-material-ui#218]
'antialiased' is less easy to read than 'subpixel-antialiased' (or 'auto').

**Comment by silvestreh** [comment]
`antialiased` renders fonts closer to what they should look like, otherwise they look semi bold. You can open your personal stylesheet located in `~/.atom/styles.less` and paste this:

```css
.tab-bar,  atom-panel {
    -webkit-font-smoothing: subpixel-antialiased;
}
```
