### ISSUE TITLE
Font Ui messing!

### ISSUE THREAD

**Issue by sajadabedi** [silvestreh/atom-material-ui#224]
In the new version of theme i have some issue with ui font, It seemed missing!
why?
![image](https://cloud.githubusercontent.com/assets/5726597/13292610/ac6a2e26-db31-11e5-8a7e-71d4ac00bc64.png)

**Comment by silvestreh** [comment]
There's not setting for UI font anymore. It's Roboto by default because, you know, it's material design after all :smile: 

You can override it in your personal stylesheet located in `~/.atom/styles.less` with this snippet:

```css
atom-workspace {
    font-family: 'Arial';        /* or whatever system font you want */
}
```
