### ISSUE TITLE
Auto hide scroll bar when not triggered or hovered, and a much thinner scrollbar

### ISSUE THREAD

**Issue by anobilisgorse** [silvestreh/atom-material-ui#274]
Hello, I really liked what you did with the new update of Atom Material UI, but I very much prefer having a thinner scrollbar and auto hiding it.

Is there some other way where I can do it through my own `styles.less`?

Many thanks.

**Comment by silvestreh** [comment]
You could try something like this in your user styles…

```scss
.scrollbars-visible-always {
    /deep/::-webkit-scrollbar {
        width: 0.25rem;
        height: 0.25rem;
    }
}
```

**Comment by anobilisgorse** [comment]
But it won't auto-hide? I came upon that too and that solved my problem about the width, but regarding the auto-hide feature?

I thought it was `.scrollbars-show-when-scrolled` but it was not working.

**Comment by silvestreh** [comment]
Scrollbar visibility is controlled by the OS. In OS X scrollbars are disabled by default, the class `scrollbars-visible-always` is added when you set the OS to always show them. Windows always shows them… I'm not sure about Linux as there are quite a few window managers/desktop environments.

With that said, you could try something like this:

```scss
.scrollbars-visible-always {
    .tree-view-scroller {
        &::-webkit-scrollbar {
            display: none;
            width: 0.25rem;
            height: 0.25rem;
        }
        &:hover::-webkit-scrollbar {
            display: block;
        }
    }
}
```

As you can see, you would have to do this on a component by component basis, targeting specifically elements with `overflow: scroll;`.

**Comment by silvestreh** [comment]
@HoverBaum the editor doesn't use OS scrollbars. Having said that, the snippet you're after would look like this:

```scss
atom-text-editor::shadow {
    .horizontal-scrollbar, .vertical-scrollbar {
        display: none;
    }
    .scroll-view:hover {
        .horizontal-scrollbar, .vertical-scrollbar {
            display: block;
        }
    }
    .scroll-view:hover:hover + .vertical-scrollbar {
        display: block;
    }
}
```
