### ISSUE TITLE
Disabled color for tree view items using light syntax theme is too dark

### ISSUE THREAD

**Issue by skyrpex** [silvestreh/atom-material-ui#41]
I use One Light. If you open a project that has a git repository with ignored items, those ignored items will be rendered in a dark color (in the tree view).

I've added this to my stylesheets:
```css
 .list-group li:not(.list-nested-item).status-ignored,
 .list-tree li:not(.list-nested-item).status-ignored,
 .list-group li.list-nested-item.status-ignored > .list-item,
 .list-tree li.list-nested-item.status-ignored > .list-item {
   color: #B2B2B2;
 }
```

Not sure if it's the best color, but works for me!
